# Generated by Django 3.1.7 on 2021-03-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Item Name')),
                ('price', models.IntegerField(verbose_name='Item Price')),
                ('description', models.TextField(verbose_name='Item Description')),
                ('stock', models.IntegerField(verbose_name='Item Current Stock')),
                ('registered_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Registered Date/Time')),
            ],
            options={
                'verbose_name': 'Byun Project Product',
                'db_table': 'byun_project_product',
            },
        ),
    ]
