# Generated by Django 3.1.7 on 2021-03-12 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210312_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('On Hold', 'On Hold'), ('Processing', 'Processing'), ('Complete', 'Complete'), ('Refund', 'Refund')], default='On Hold', max_length=32, verbose_name='Status'),
        ),
    ]
